### PR TITLE
Fixed indents taking precedence over MIN

### PR DESCRIPTION
**Pull request by erikknaake**
Fixed indents taking precedence over MIN, which causes problems when evaluating subtraction expressions.

### CODE REVIEW

**Comment by sanmai-NL** [comment]
You mean idents. @DennisBreuker, is this the best approach to fixing the issue in your opinion?

**Comment by DennisBreuker** [comment]
This is *not* the correct way to fix this.
The problem lies in the definition of LOWER_IDENT. That is wrong.
It should be the same construction as CAPITAL_IDENT:

LOWER_IDENT: [a-z] [a-z0-9\-]+;

This also fixes the MIN problem.

**Comment by erikknaake** [comment]
> This is _not_ the correct way to fix this.
> The problem lies in the definition of LOWER_IDENT. That is wrong.
> It should be the same construction as CAPITAL_IDENT:
> 
> LOWER_IDENT: [a-z] [a-z0-9-]*;
> 
> This also fixes the MIN problem.

That also has the problem that ICSS can not support browser specific css extensions such as:
https://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_Extensions

**Comment by michelportier** [comment]
Fixed.

**Pull request closed without merging**
